### ISSUE TITLE
Question: How/when should Goals be evaluated and set?

### ISSUE THREAD

**Issue by jzapdot** [crashkonijn/GOAP#130]
**Expected behavior**
_A clear and concise description of what you expected to happen._

It seems that within the GOAP framework that agents have a single fixed goal that the planner continues to make plans towards. Goals themselves are set externally to the agent/framework itself. 
* Where/when do you recommend evaluating goals and setting them onto agents?
* Related to goal evaluation and setting, where/when do you handle interrupting plans in-progress?

**Code**
This is an example in the `ComplexAgentBrain` from the demo of an external demo class that evaluates and and sets goals based on the type of agent and the current world state.

```csharp
        private void DetermineGoal()
        {
            switch (this.agentType)
            {
                case AgentType.Miner:
                    this.DetermineMinerGoals();
                    break;
                case AgentType.WoodCutter:
                    this.DetermineWoodCutterGoals();
                    break;
                case AgentType.Smith:
                    this.DetermineSmithGoals();
                    break;
                case AgentType.Cleaner:
                    this.DetermineCleanerGoals();
                    break;
            }
        }
```

**Unity Version**
**Unity 2022.3.14f1**

**Unity.Collections Version**
**v1.4.0**

**Package Version**
**v2.1.16**

**Additional context**
I could see there being more built-in support and/or a more defined mechanism for evaluating a set of goals to determine which are eligible, and then picking from the eligible subset based on priority or some other heuristic. Have you ever considered including goal evaluation, interruptions, and setting as being something the GOAP library would more directly influence or do you see this mostly as a responsibility for the consuming developer to determine how this should be done?

**Comment by crashkonijn** [comment]
Hi there!

I have thought about adding something that could decide your goal, however that's very game dependent and technically not part of GOAP (which is an action planner).

Deciding what the best goal is is very game dependent and as such is something I haven't implemented. This could be an FSM (like in the examples), Behaviour Trees or even (simple) Utility AI or GOAP itself. Since what would the best approach I've chosen to not provide anything at all since that could become quite a big layer on top, probably requiring adding interruptions etc as well.

There's one option that could be implemented fairly easily that would still leave enough room for any implementor to decide how goals work.

In GOAP one always uses the concept of goals and actions, but whenever you implement them you realize the distinction between the two is mostly to help ourselves understand the system. The two parts of GOAP (building the graph and resolving it) don't really care. Deep down a goal is just a node without effects.

A goal is simply a conceptual entry point into the graph :)

That being said, it is fairly easy to add a `GetCost` method to a goal, and to let goals being connected on top of other goals. For example, we could (by default) add a `RootGoal` which is always connected to all the other goals. Simply setting the `RootGoal` as the goal would then evaluate the whole graph and each goal.

Something that this would require as well is what I like to call 'dynamic resolving', which is re-evaluating if the current thing you're doing is still the best thing to do. Luckily support for this is already added in v3!

Anyway, all this would essentially be the same as adding a 2nd GOAP on top to determine your goal.

**Comment by shashank42** [comment]
> That being said, it is fairly easy to add a GetCost method to a goal, and to let goals being connected on top of other goals. For example, we could (by default) add a RootGoal which is always connected to all the other goals. Simply setting the RootGoal as the goal would then evaluate the whole graph and each goal.

I like this approach, could you give a brief way how to do this? Do you mean conceptually keep only one RootGoal and let the costs of each action be multiplied by the conceptual sub-goal's weights (say, assuming Utility AI).

**Comment by crashkonijn** [comment]
> I like this approach, could you give a brief way how to do this? Do you mean conceptually keep only one RootGoal and let the costs of each action be multiplied by the conceptual sub-goal's weights (say, assuming Utility AI).

> I see that you have already added SetBaseCost and GetCost on goals but SetBaseCost is not used anywhere in the system. Manually adding a SetBaseCost and evaluating the best goal could be wrong as the best cost will only be revealed on solving the graph for each goal. Am I following your logic?

Fun fact, when googling "goap" and looking for images you will find a screenshot of the 2016 version that I used to build my graduation project with:
![image](https://github.com/crashkonijn/GOAP/assets/5364802/325ac2a7-d325-47bc-a9a0-846caad848cb)

The upper row are the different goals the agent had access to, and as you can see this also included a cost (exactly the same as on an action). By increasing or decreasing the cost I could steer an agent towards certain behaviour. The cost of the goal would simply be added when resolving, and the agent would perform the cheapest action it could find for any goal (that wasn't disabled).

> I'm finding it complex to figure out a way to make a Utility AI approach on top of the framework since in every update loop the Agentbehaviour>SetAction the action's Start function is called followed by AgentBehaviour>Run which performs the action as well, giving no time between finding the optimal action and action path and executing it.

Is there a chance you're calling the SetGoal<>(true) method every frame? Or is each action completed immediately?

A new action is only resolved when an agent doesn't have a running action anymore. SetAction is only called when a new action has been resolved

**Comment by shashank42** [comment]
So you mean that if I SetGoal for multiple goals in one update loop, the system will figure out the best action across all goals based on the costs provided. It did not appear so to me because the Goap runners use CurrentGoal to select the Goal to find the best Action path for. 
In the following example it will either choose an action to wander or to attack the enemy based on cost of the final action selected by solving the graph.

`
// Inside AgentBrain>FixedUpdate()
 this.agent.SetGoal<HurtEnemyGoal>(false);
 this.agent.SetGoal<WanderAroundGoal>(false);
`

> Is there a chance you're calling the SetGoal<>(true) method every frame? Or is each action completed immediately?

Yes, should I not?

> A new action is only resolved when an agent doesn't have a running action anymore. SetAction is only called when a new action has been resolved

So while the action returns ActionRunState.Continue the same action executer will be called. But what if in the next update loop the A* concludes that another action+goal combination is better?

**Comment by crashkonijn** [comment]
> So you mean that if I SetGoal for multiple goals in one update loop, the system will figure out the best action across all goals based on the costs provided. It did not appear so to me because the Goap runners use CurrentGoal to select the Goal to find the best Action path for.

No this doesn't work, an agent has one single active goal.

> Yes, should I not?

There can only be one single active goal. If you change goal every frame (and force stop the current running action), than indeed the resolver will run every frame and choose a new action.

> So while the action returns ActionRunState.Continue the same action executer will be called. But what if in the next update loop the A* concludes that another action+goal combination is better?

The resolver is run when there is no active action. The active action get's cleared when the ActionRunState.Stop is returned in an action, or when the SetGoal is called with true (stop action).

Just to make sure; I'm now talking about how the current system works. Not about theoretically having a root goal.

**Comment by shashank42** [comment]
Understood the action interruption and new action resolution now. I misunderstood the image you put where you had multiple goals simultaneously.

So theoretically having a root goal is possible but I don't see how apart from each action be multiplied by the conceptual sub-goal's weights.
