### ISSUE TITLE
Question: Using this for tile-based game?

### ISSUE THREAD

**Issue by Sandkvist** [crashkonijn/GOAP#141]
Hey 

I just wanted to hear your thoughts on the viability of using this awesome system for a tile-based game? Do you see any foreseeable obstacles? I see alot of the Targets rely on a Vector3, whereas I will be using Vector3Int for my grid, but that should just be a simple conversion.

Any sort of dependencies that would make this problematic?

**Comment by crashkonijn** [comment]
Hi @Sandkvist!

Thanks for giving this project a go and reaching out!

You can create any type of Target class, as long as it implements the `ITarget` interface. That interface only requires a Vector3 Position to be available, this is used for distance measurement when calculating the next action.

Aka you could do this, or any other type that fits your game.
```
public class TileTarget : ITarget
    {
        public Vector3Int Tile { get; }
        public Vector3 Position => this.Tile.Vector3;

        public TileTarget(Vector3Int tile)
        {
            this.Tile = tile;
        }
    }
```

Since you're making a tile based game; if it's also supposed to be turn-based, that's a bit harder with the current version. See #64. This will be properly possible with the next major version: #120.

**Comment by crashkonijn** [comment]
I'm assuming the issue has been resolved.

If there's any further questions don't hesitate to reach out!

**Comment by Sandkvist** [comment]
I got it working, thank you!
