### ISSUE TITLE
Proposal

### ISSUE THREAD

**Issue by gojas** [crashkonijn/GOAP#2]
https://github.com/crashkonijn/GOAP/blob/a34770a0ed01125ecf08b4c83663f613079a58c1/GOAP/Core/GoapAgent.cs#L130

First of all, great library, liked it more than ReGoap 👍 

But quick question... Why this line?
I'm pretty sure this should be **precondition** of the action?

**Comment by crashkonijn** [comment]
Hello @gojas , thanks for giving my GOAP a go! :)

So basically an Action has a required range (which can also be infinite) before it should perform that action. If the Agent isn't within that range the agent will try to move closer to the target first.

Anyway, the action that's being executed there has already passed the preconditions etc.

I guess that line could maybe be made a bit clearer, since it also took me some time right now to figure it out.

**Comment by gojas** [comment]
You are welcome... :)

"If the Agent isn't within that range the agent will try to move closer to the target first."
That is the thing i am referring to, i just think that that part should not be Agents responsibility, but Actions...

If Action is GrabItemAction your Perform method of that action should move Agent to the Item...

This is just suggestion of course, i will most certainly use the library, only this part was confusing me :)

**Comment by crashkonijn** [comment]
Ah you're quick to reply! I just figured [this image](https://puu.sh/xL5t4/fc81a10926.png) might make some of it a bit more clear.

I guess there is indeed be a simple FSM behind it, which basically is perform, move or idle (do nothing).

It would be really easy to implement an "official" idle action if I'd play it in an else statement after this line, I'll update that tomorrow :)

https://github.com/crashkonijn/GOAP/blob/a34770a0ed01125ecf08b4c83663f613079a58c1/GOAP/Core/GoapAgent.cs#L126

**Comment by crashkonijn** [comment]
#https://github.com/crashkonijn/GOAP/commit/e7fa37bb6def3c9d109b3c2a91619f80ce1c6db2
