### ISSUE TITLE
Bug:  documentation Tutorials It won't move when it's done.

### ISSUE THREAD

**Issue by SyaoranChang** [crashkonijn/GOAP#230]
**Describe the bug**
https://goap.crashkonijn.com/introduction/gettingstarted#setup-in-unity
1.documentation Tutorials It won't move when it's done.
2. The tutorials for goap-v3 are old like goap-v2, it would be helpful if they were updated.

**Steps to Reproduce**
1. It won't move when it's done.

**Expected behavior**
1. It will move when it's done.

**Additional context**
WanderTargetSensor.cs 
Change the code from above to below and it will move.
private Vector3 GetRandomPosition(IMonoAgent agent)
{
    var random =  Random.insideUnitCircle * 5f;
    var position = agent.transform.position + new Vector3(random.x, 0f, random.y);

    return position;
}

private Vector3 GetRandomPosition(IMonoAgent agent)
{
    var random = Random.insideUnitCircle * 5f;
    var position = agent.transform.position + new Vector3(random.x, 0f, random.y);
        
    if (position.x > -Bounds.x && position.x < Bounds.x && position.z > -Bounds.y && position.z < Bounds.y)
        return position;

    return this.GetRandomPosition(agent);
}

**Comment by crashkonijn** [comment]
Hi there!

Thanks for giving the project a go and reaching out!

V3 is currently still in beta because the docs haven't been updated yet, including the getting started.

The getting started is very similar to the demo scenes (which already have been upgraded to work in v3), I would suggest having a look there to see if you can spot the difference, or use that as your starting point.

Unfortunately this is not my job and I have can only work on it whenever my free time allows for it.

If you'd like a bit more hands on support you can hop on our Discord server, there's more people there that can help out.

**Comment by crashkonijn** [comment]
Hi again!

I've spent quite a bit of time the last few days on working on the docs.

The [Getting Started](https://goap.crashkonijn.com/v/goap-v3/readme/gettingstarted) and the [Setup](https://goap.crashkonijn.com/v/goap-v3/readme/gettingstarted/setup) should explain the basics and help you setup a working wander/idle again!
