### ISSUE TITLE
Feature: Access to components inside of the GetCost override. 

### ISSUE THREAD

**Issue by Unshackled-Games** [crashkonijn/GOAP#232]
After a short discussion in Discord, I wanted to write this Feature Request. It would be very handy to get access to data like nutritious for the GetCosts for a custom handling. 

https://discord.com/channels/1093598557480685578/1093599290829590679/1283830094690783384

![image](https://github.com/user-attachments/assets/dd0540bc-8317-4178-93cd-46e56ab9c212)

**Comment by ajmalrizni** [comment]
Ditto on this request!

Different targets have different properties, and it would make sense for the GOAP agent to take those properties into account when formulating a plan. Ideally, the action's Data object (or the object's fields) would be exposed in the GetCost function. If that's not possible, maybe the same behaviour could be achieved just by passing a sensor/target.

One example of where this could be useful is if an agent is formulating a plan to fix their hunger. The way it currently works, the agent would consider all food options to be equal, possibly leading them to eat small nearby snacks or even possibly rotting food. If the GetCost function can take its target/object data into account, then they could be more motivated to execute a plan to cook a filling meal, because the nutrition value of the food outweighs the effort/cost of cooking a meal. 

I think this change could allow for much more expressive AI agents that behave more realistically and intelligently.

**Comment by Racines** [comment]
Indeed, this would be a great addition!

**Comment by crashkonijn** [comment]
This was released in the [3.0.13-beta](https://github.com/crashkonijn/GOAP/releases/tag/3.0.13-beta)!
