### ISSUE TITLE
Bug: Test folder is included in Unity Asset Store package

### ISSUE THREAD

**Issue by sjoshua270** [crashkonijn/GOAP#311]
**Describe the bug**
It seems the Tests folder was included in the Unity Asset Store package. This causes errors complaining about NSubstitute not being installed.

**Steps to Reproduce**
1. Import GOAP v3.0.0 into a Unity (6) project
2. Do not change any import options
3. Don't have NSubstitute or other testing libraries installed
4. Observe debug errors

**Expected behavior**
No errors when importing GOAP v3

**Screenshots**
![image](https://github.com/user-attachments/assets/eab0c9d2-efe4-41f8-9d01-fd938337925d)

**Unity Version**
Unity 6000.0.26f1

**Package Version**
GOAP v3.0.0

**Additional context**
You can fix these errors by removing the Tests folder

**Comment by crashkonijn** [comment]
Hey @sjoshua270!

I've just reworked my release pipeline for v3. It now removes the test folder.

Thanks for mentioning this, I always test anything I upload by importing it into an empty project (which apparently did have these package installed...).

I just submitted the update to the Asset Store, so this should be fixed in a couple days!

**Comment by sjoshua270** [comment]
Happy to help!

**Comment by crashkonijn** [comment]
3.0.24 should be live in the asset store by now, without the folder!
