### ISSUE TITLE
Feature: Unit Tests for Goal Completion

### ISSUE THREAD

**Issue by Juskelis** [crashkonijn/GOAP#68]
**Is your feature request related to a problem? Please describe.**
I think there might be a bug where OnGoalCompleted is never called, but I'm not sure if its me or the underlying systems. It would be nice to have a Unit Test to reference how I should be setting up my system so that I receive OnGoalCompleted correctly.

**Describe the solution you'd like**
A Unit Test that makes sure that, given a goal with a condition, and an action that modifies state to meet that condition, goal completion logic is reached.

**Describe alternatives you've considered**
I considered just asking about this in the discord, but it would be better to have a code solution to prevent people from continuously asking in the future. I also considered making a bug about this, but I'm not familiar enough with the innards of this project to confidently say that I'm seeing a bug.

**Additional context**
The Complex Example has the brain listen for OnGoalCompleted, but if you put a breakpoint on it, it never seems to be hit.

**Comment by crashkonijn** [comment]
Hi there!

Thanks for trying out the project and writing such a descriptive ticket!

Usually when the event isn't called the conditions of the goal are never met (because they don't have a sensor).

The goal completion event is something that was introduced after the demos where made and as such are not properly used there.

There's a couple more points that could be improved, but I don't currently have time to do that.

As for the unit test, I agree that should be there and I thought I did make it. Unfortunately I moved to a new house recently and still don't have internet (should be fixed this week). A quick look on my phone didn't help.

I will leave this ticket open as a reminder that I need to look into this once I can properly access the project again!

In the meantime please make sure that you've properly setup the sensors for the conditions of the goal.

Please let me know if this helps!

**Comment by crashkonijn** [comment]
Hi again!

The WorldState that is being 'sensed' is stored in a format that the planner can understand (integers). The WorldState that is used within the GOAP should not be the single source of truth. The actual state/data of a game should be stored in your own component, and can be represented in much more complex data than ints. The sensors are used as a translation layer between the actual data and the GOAP, which are only called when it needs to find a new action.

This way the GOAP is 'decoupled' from the rest of your game as much as possible. This also makes sure that it's relatively easy to add the GOAP later in the development of a game.

**Comment by crashkonijn** [comment]
Hi there!

Since I haven't heard anything back I'm assuming you have all the information you need.

For those looking for this, technically there are [2 unit tests](https://github.com/crashkonijn/GOAP/blob/master/Package/Tests/CrashKonijn.Goap.Tests/UnitTests/GoapSetJobRunnerTests.cs#L152) covering this. Although they do test this in a much deeper level than your usual setup.
