### ISSUE TITLE
Feature: Improve documentation

### ISSUE THREAD

**Issue by crashkonijn** [crashkonijn/GOAP#79]
**Is your feature request related to a problem? Please describe.**
The documentation should be improved to explain concepts more clearly.

**Describe the solution you'd like**
A lot of documentation is pretty 'bare bone'. I've already done some tests to improve documentation using ChatGPT to fill in the blank.

**Comment by NicholasDewberryOfficial** [comment]
If at all possible, I'd like to expand by adding more e
xamples/comments to the code myself. Were you thinking about adding to every page on the documentation, or did you have a specific few pages in mind? 

For my senior project we are developing a video game using this framework, and I can go in-depth with how we got it working.  Would you be interested in seeing that?

**Comment by crashkonijn** [comment]
Hi there @NicholasDewberryOfficial!

I was indeed planning on improving all of the documentation. In regards with commenting code itself, I firmly believe that code should speak for itself. When writing too much comments they can quickly become out of date with the real world (the actual code). Are there any specific/complex parts you'd like more explanation for?

If you're up for mee we could have a discord call sometime? Would be amazing to see the work you've done! Learning what works and what doesn't from people that actually use the project is very valuable information for me 😄

**Comment by NicholasDewberryOfficial** [comment]
Sure, I would like a discord call. I'd have to schedule it during December tho. We're still working out systems and even though your asset has been very helpful, there's a lot of design work on our end that make it a little bit difficult to show off what we have.

To give a high-level description of what we are doing, we are using your framework in order to add complex enemies in our first person shooter. We want to have multiple types of enemies, and we want them to communicate, and we want their goals to be the same even though they all have different ways of interacting with the environment. 

It's a little bit spaghetti because I ended up creating one goapSet for every enemy in the game, and I told them what actions they could take by assigning conditions to every action. 

As for parts that I was having lots of trouble understanding, I'd like a section where you run through the complex demo and explain how you set everything up exactly. What you have is a good "this is how everything works" overview, but I'd prefer a section where you go over "this is how to make it" in detail (like you had for the wander target example). 

In order to get my own understanding, I've been keeping my own set of notes while working on my project. 

Thanks for this asset!

**Comment by crashkonijn** [comment]
Sounds awesome!

Care to share those notes with me? I think they could prove very useful for me to see where the docs are lacking.

I'm actually working with [TooLoo](https://youtube.com/@tooloo3658?si=FtInCgq__5g20wyn)  on a tutorial series for this project. I think that would be what you're looking for 🙂
