### ISSUE TITLE
Feature: Keep WorldKeyBuilder to query the keys

### ISSUE THREAD

**Issue by Caresilabs** [crashkonijn/GOAP#94]
**Is your feature request related to a problem? Please describe.**
The `WorldKeyBuilder `is lost after the GoapSetBuilder is built. I'd like to query the `agent.WorldData.IsTrue` by using generics, and in order for me to do that we need an instance of the key which doesn't seem possible due to the lost `WorldKeyBuilder`.

The purpose of this is for the brain to be able to query the world state (maybe even the global?) to choose the best Goal in the current state.

**Describe the solution you'd like**
It would be preferable to have access to the `WorldKeyBuilder`, alternativley be able to do something like `agent.WorldData.IsTrue<IsHungry>(...)`. I know WorldData.States exists but looping over it is O(n) instead of O(1).

**Comment by crashkonijn** [comment]
Hi there!

It is usually not advised to actually query the WorldData on the agent, this information is usually out of date.

Running the sensors can be quite heavy, so it is only run right before the planner is choosing the next best action. In the future I also plan to add an optimization where only the relevant sensors for a goal are being run, so that would make most data even more out of date.

The WorldState on the agent is an integer based representation of the world, which isn't the best format to store all sorts of data. The world state should contain (only) data which is relevant to the agent at the time of deciding the next best action, it should never be the source of truth.

The 'source of truth' should just be in your 'normal' game data, for example as values on your MonoBehaviours in your game. If you want something similar to the WorldData I'd suggest you make your own data store which can handle more data types than just integers. A sensor would simply read data from your own data store and transform it's values to ints.

**Comment by Caresilabs** [comment]
Thank you for your very detailed answer. Now when you say it, it does makes a lot of sense to keep a different source of truth than the sensors' cache.

I'm still learning GOAP and from the example I may have misinterpreted the WorldData as a form of truth.

Anyway, great job with the lib!
Closing this as the feature of a Truth Store is out of scope.

**Comment by crashkonijn** [comment]
I did believe I did clarify this in the docs recently, but I haven't been able to find it. I'll make sure this is a specific topic in the docs.

Thanks for the report and your kind words!
